### access public resource:
GET http://localhost:3001/posts



### access protected resource without cred:
GET http://localhost:3001/protected-posts



### login
POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "Nuzz"
}



### refresh token with http_only cookie
GET http://localhost:3001/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik51enoiLCJpYXQiOjE2NzMxMTU1MzcsImV4cCI6MTY3MzIwMTkzN30.eEwtNYonnX7IiVLiwzCSQWdhU4xfoR56-ElfJCcE7JA



### access protected resource with invalid cred:
DELETE http://localhost:3001/post
Authorization: Bearer wrongFalseNullwrongFalseNullwrongFalseNull.wrongFalseNullwrongFalseNullwrongFalseNull.wrongFalseNullwrongFalseNullwrongFalseNull

### access protected resource with valid cred:
DELETE http://localhost:3001/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik51enoiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE2NzMxMTU1NzksImV4cCI6MTY3MzExNTYwOX0.CqcRAZvYrlI6SEScx9ReIm4ZomhviFqzA-YrhRD_7Us



### logout
DELETE http://localhost:3001/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTnV6eiIsIm1ldGEiOnsiZ2VuZGVyIjoibWFsZSJ9LCJpYXQiOjE2NzI5Njc1ODN9.hK-k_DE-8_yLOVZQE9adh5e1VWE19jlgu4Wg4gUyIzc"
}